<?php
//Jackie Salim
//PHP code for the first page. This page displays the boat information
//in a table. It displays the owner's name, Marina name, and Slip number of the boat.
  $pageTitle = "Create Agent";
  include("header.html");
  require_once("conn.php");

  //echo $pageTitle;
  echo '<br>';

  echo 'AGENTS:<br>';
  // Create AGENT table
  echo '<table align="center" border=1>';
     echo '<tr>';
       echo '<td width="150" align="center">';
         echo 'Agent ID';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Agent Type';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'First Name';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Middle Initial';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Last Name';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Street';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'City';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'State';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Zip';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Email';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Cell Number';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Office Number';
       echo '</td>';
     echo '</tr>';

  foreach($conn->query('SELECT AgentId,FirstName,MiddleInit,LastName,Street,City,State,Zip,Email,OfficeNum,CellNum,Type FROM Agent') as $row)
  {
   echo '<tr>';
     echo '<td align="center">';
         echo $row['AgentId'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Type'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['FirstName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['MiddleInit'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['LastName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Street'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['City'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['State'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Zip'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Email'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['CellNum'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['OfficeNum'];
     echo '</td>';
   echo '</tr>';
  }
 echo '</table>';

 echo '<br><br>VENDORS:<br>';

 // Create VENDOR table
 echo '<table align="center" border=1>';
     echo '<tr>';
       echo '<td width="100" align="center">';
           echo 'Vendor ID';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'Vendor Type';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'Business Name';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Rep First Name';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Rep Last Name';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Street';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'City';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'State';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Zip';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Email';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Cell Number';
     echo '</tr>';

  foreach($conn->query('SELECT VendorId,BusinessName,RepFirstName,RepLastName,Street,City,State,Zip,RepEmail,Type,RepCellNum FROM Vendor') as $row)
  {
   echo '<tr>';
     echo '<td align="center">';
         echo $row['VendorId'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Type'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['BusinessName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['RepFirstName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['RepLastName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Street'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['City'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['State'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Zip'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['RepEmail'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['RepCellNum'];
     echo '</td>';
   echo '</tr>';
  }

 echo '</table>';


 echo '<br>EVENTS:<br>';

 // Create EVENT table
 echo '<table align="center" border=1 width="100%">';
     echo '<tr nowrap>';
       echo '<td align="center">';
           echo 'Event ID';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'Event Name';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'Seating Capacity';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'Manager';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Vendor';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Singer';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Date';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Time';
      echo '</tr>';
       echo '<td width="100" align="center">';
         echo 'Street';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'City';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'State';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Zip';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Status';
       echo '</tr>';

  foreach($conn->query('SELECT EventId,EventName,SeatingCapacity,BusinessName,FirstName,LastName,Date,StartTime,Status,Singer,Event.Street,Event.City,Event.State,Event.Zip FROM Event,EventManager,Vendor WHERE Event.EventManagerId = EventManager.EventManagerId AND Event.VendorId = Vendor.VendorId') as $row)
  {
   echo '<tr>';
     echo '<td align="center">';
         echo $row['EventId'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['EventName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['SeatingCapacity'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['FirstName'].' '.$row['LastName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['BusinessName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Singer'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Date'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['StartTime'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Street'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['City'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['State'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Zip'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Status'];
     echo '</td>';
   echo '</tr>';
  }
 echo '</table>';

 echo '<br><br>';

echo 'ARTISTS:<br>';
  // Create ARTIST table
  echo '<table align="center" border=1>';
     echo '<tr>';
       echo '<td width="150" align="center">';
         echo 'Artist ID';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'First Name';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Middle Initial';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Last Name';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Gender';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Street';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'City';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'State';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Zip';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Email';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Cell Number';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Rate per Event';
       echo '</td>';
       echo '<td width="150" align="center">';
         echo 'Agent';
       echo '</td>';
     echo '</tr>';

  foreach($conn->query('SELECT ArtistId,Artist.FirstName,Artist.MiddleInit,Artist.LastName,Gender,Artist.Street,Artist.City,Artist.State,Artist.Zip,Artist.Email,Artist.CellNum,RatePerEvent,Agent.FirstName as fname,Agent.LastName as lname FROM Artist,Agent where Artist.AgentId = Agent.AgentId') as $row)
  {
   echo '<tr>';
     echo '<td align="center">';
         echo $row['ArtistId'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['FirstName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['MiddleInit'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['LastName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Gender'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Street'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['City'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['State'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Zip'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Email'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['CellNum'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['RatePerEvent'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['fname'].' '.$row['lname'];
     echo '</td>';
   echo '</tr>';
  }
 echo '</table>';

 echo '<br><br>';

 echo 'BANDS:<br>';
  // Create BAND table
  echo '<table align="center" border=1>';
     echo '<tr>';
       echo '<td width="100" align="center">';
         echo 'Band ID';
       echo '</td>';
       echo '<td width="90" align="center">';
         echo 'Band Name';
       echo '</td>';
       echo '<td width="100" align="center">';
           echo 'Leader';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Member 1';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Member 2';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Member 3';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Member 4';
       echo '</td>';
       echo '<td width="80" align="center">';
         echo 'Member 5';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Member Count';
       echo '</td>';
       echo '<td width="80" align="center">';
         echo 'Rate';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Leader Phone';
       echo '</td>';
       echo '<td width="200" align="center">';
         echo 'Notes';
       echo '</td>';
       echo '<td width="100" align="center">';
         echo 'Agent';
       echo '</td>';
     echo '</tr>';
  foreach($conn->query('SELECT BandId,BandName,Leader,Member1,Member2,Member3,Member4,Member5,MemberCount,RatePerEvent,Notes,Band.CellNum,FirstName,LastName FROM Band,Agent where Band.AgentId = Agent.AgentId') as $row)
  {
   echo '<tr>';
     echo '<td align="center">';
         echo $row['BandId'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['BandName'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Leader'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Member1'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Member2'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Member3'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Member4'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Member5'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['MemberCount'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['RatePerEvent'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['CellNum'];
     echo '</td>';
     echo '<td align="center">';
         echo $row['Notes'];
     echo '</td>';
     echo '<td align="center">';
          echo $row['FirstName'].' '.$row['LastName'];
     echo '</td>';
   echo '</tr>';
  }
 echo '</table>';

 include("footer.html");

?>
